begin;
do $$
declare owner_id uuid:=gen_random_uuid(); support_id uuid:=gen_random_uuid(); teacher_id uuid:=gen_random_uuid(); other_id uuid:=gen_random_uuid();
  owner_session uuid:=gen_random_uuid(); support_session uuid:=gen_random_uuid(); student_id uuid:=gen_random_uuid(); review_id uuid:=gen_random_uuid();
  ticket_id uuid; announcement_id uuid; expense_id uuid; d jsonb; section text;
begin
  insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values
    (owner_id,owner_id||'@example.invalid',now(),'{}'),(support_id,support_id||'@example.invalid',now(),'{}'),
    (teacher_id,teacher_id||'@example.invalid',now(),'{"role":"owner"}'),(other_id,other_id||'@example.invalid',now(),'{}');
  insert into private.admin_members(user_id,role) values(owner_id,'owner'),(support_id,'support');
  insert into auth.sessions(id,user_id,aal,created_at,updated_at) values(owner_session,owner_id,'aal2',now(),now()),(support_session,support_id,'aal2',now(),now());
  insert into public.students(id,user_id,full_name,school_level,grade_level) values(student_id,teacher_id,'ERP QA','SD','4');
  insert into public.app_reviews(id,user_id,rating,comment) values(review_id,teacher_id,4,'Review QA asli');
  perform set_config('request.jwt.claim.sub',teacher_id::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',teacher_id,'aal','aal2','session_id',owner_session,'user_metadata',jsonb_build_object('role','owner'))::text,true);
  perform set_config('role','authenticated',true);
  if public.get_admin_access()->>'role' is not null then raise exception 'Metadata escalated role'; end if;
  begin perform public.admin_read('accounts');raise exception 'Teacher admin access allowed';exception when insufficient_privilege then null;end;
  begin perform count(*) from private.admin_members;raise exception 'Private table exposed';exception when insufficient_privilege then null;end;
  d:=public.teacher_support('create','{"subject":"Masalah QA","message":"Pesan dukungan pengujian","category":"bug"}');ticket_id:=(d->>'id')::uuid;
  if jsonb_array_length(public.teacher_support('tickets'))<>1 or public.teacher_support('tickets')->0?'internal_note' then raise exception 'Teacher ticket DTO leaked';end if;
  perform set_config('request.jwt.claim.sub',other_id::text,true);
  if jsonb_array_length(public.teacher_support('tickets'))<>0 then raise exception 'Foreign ticket visible';end if;
  perform set_config('request.jwt.claim.sub',owner_id::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'aal','aal1','session_id',owner_session)::text,true);
  begin perform public.admin_read('dashboard');raise exception 'AAL1 access allowed';exception when insufficient_privilege then null;end;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'aal','aal2','session_id',support_session)::text,true);
  begin perform public.admin_read('dashboard');raise exception 'Foreign session MFA allowed';exception when insufficient_privilege then null;end;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'aal','aal2','session_id',owner_session)::text,true);
  foreach section in array array['dashboard','accounts','reviews','tickets','announcements','services','expenses','settings','audit','reports'] loop
    d:=public.admin_read(section);if d is null then raise exception 'Missing admin section %',section;end if;
  end loop;
  if exists(select 1 from public.students where id=student_id) then raise exception 'Admin gained business table access';end if;
  perform public.admin_mutate('review',jsonb_build_object('id',review_id,'status','resolved','note','Catatan internal'));
  perform public.admin_mutate('ticket',jsonb_build_object('id',ticket_id,'status','resolved','priority','high','reply','Balasan untuk guru','internal_note','Catatan rahasia'));
  perform public.admin_mutate('account',jsonb_build_object('id',teacher_id,'status','suspended','reason','Penangguhan pengujian'));
  perform set_config('request.jwt.claim.sub',teacher_id::text,true);
  if exists(select 1 from public.students where id=student_id) then raise exception 'Suspended session can read';end if;
  begin perform public.get_dashboard_stats();raise exception 'Suspended definer bypass';exception when insufficient_privilege then null;end;
  begin insert into public.students(user_id,full_name,school_level,grade_level) values(teacher_id,'Diblokir QA','SD','3');raise exception 'Suspended insert allowed';exception when insufficient_privilege then null;end;
  perform set_config('request.jwt.claim.sub',owner_id::text,true);
  perform public.admin_mutate('account',jsonb_build_object('id',teacher_id,'status','active','reason',''));
  d:=public.admin_mutate('announcement_save',jsonb_build_object('title','Pengumuman QA','body','Isi pengumuman hanya untuk fixture QA','target_emails',jsonb_build_array(teacher_id||'@example.invalid'),'publish_at',now(),'expires_at',now()+interval '1 day'));announcement_id:=(d->>'id')::uuid;
  perform public.admin_mutate('announcement_publish',jsonb_build_object('id',announcement_id));
  d:=public.admin_mutate('expense',jsonb_build_object('expense_date',current_date,'category','hosting','description','Biaya platform QA','amount',125000));expense_id:=(d->>'id')::uuid;
  perform public.admin_mutate('expense_archive',jsonb_build_object('id',expense_id));
  perform set_config('request.jwt.claim.sub',support_id::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',support_id,'aal','aal2','session_id',support_session)::text,true);
  perform public.admin_read('accounts');perform public.admin_read('reviews');perform public.admin_read('reports');
  begin perform public.admin_read('settings');raise exception 'Support settings allowed';exception when insufficient_privilege then null;end;
  begin perform public.admin_mutate('account',jsonb_build_object('id',teacher_id,'status','suspended','reason','QA'));raise exception 'Support suspension allowed';exception when insufficient_privilege then null;end;
  perform set_config('role','postgres',true);
  if (select comment from public.app_reviews where id=review_id)<>'Review QA asli' or (select rating from public.app_reviews where id=review_id)<>4 then raise exception 'Review original changed';end if;
  if (select count(*) from public.notifications where ref_key='announcement:'||announcement_id)<>1 or not exists(select 1 from public.notifications where user_id=teacher_id and ref_key='announcement:'||announcement_id) then raise exception 'Targeted announcement incorrect';end if;
  perform private.publish_announcements();
  if (select count(*) from public.notifications where ref_key='announcement:'||announcement_id)<>1 then raise exception 'Announcement duplicated';end if;
  update private.admin_members set active=false where user_id=support_id;
  perform set_config('role','authenticated',true);
  begin perform public.admin_read('accounts');raise exception 'Revoked role JWT still works';exception when insufficient_privilege then null;end;
  perform set_config('role','postgres',true);
  delete from auth.sessions where id=owner_session;
  perform set_config('request.jwt.claim.sub',owner_id::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'aal','aal2','session_id',owner_session)::text,true);
  perform set_config('role','authenticated',true);
  begin perform public.admin_read('accounts');raise exception 'Revoked MFA session works';exception when insufficient_privilege then null;end;
  perform set_config('role','postgres',true);
  if not exists(select 1 from public.students where id=student_id) then raise exception 'Teacher records deleted';end if;
  if not exists(select 1 from private.platform_expenses where id=expense_id and archived_at is not null) then raise exception 'Expense archive failed';end if;
end $$;
rollback;
