import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { ResourceEditor,ResourceDelete,HomeworkStatusButton } from "@/components/learning/resource-editor";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { DateText } from "@/components/shared/date-text";
import { formatInTimeZone } from "date-fns-tz";
import type { LearningFile } from "@/types/learning.types";
export async function LearningPage({kind,query}:{kind:"material"|"homework";query:Record<string,string|undefined>}) {
  const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)throw new Error("Silakan masuk kembali.");
  const tabs=kind==="material"?[["collection","Koleksi Saya"],["sessions","Dari Pertemuan"]]:[["assigned","Ditugaskan"],["completed","Selesai"]];const tab=tabs.some(t=>t[0]===query.tab)?query.tab!:tabs[0]![0]!;
  const path=kind==="material"?"/materials":"/homework";const q=(query.q??"").slice(0,100).replace(/[%,_]/g,"");const page=Math.max(1,Number.parseInt(query.page??"1",10)||1);const from=(Math.min(page,100000)-1)*20;
  const [{data:students,error:studentsError},{data:profile}]=await Promise.all([db.from("students").select("id,full_name").eq("user_id",user.id).is("deleted_at",null).order("full_name"),db.from("profiles").select("timezone").eq("id",user.id).single()]);
  if(studentsError)throw new Error("Murid belum dapat dimuat.");const names=new Map((students??[]).map(s=>[s.id,s.full_name]));const tz=profile?.timezone??"Asia/Jakarta";
  let rows:React.ReactNode[]=[];let total=0;
  if(kind==="material"&&tab==="sessions") {
    const {data,error,count}=await db.from("sessions").select("id,student_id,session_date,material,sub_material,learning_notes",{count:"exact"}).eq("user_id",user.id).not("material","is",null).ilike("material",`%${q}%`).order("session_date",{ascending:false}).order("id").range(from,from+19);if(error)throw new Error("Materi belum dapat dimuat.");total=count??0;
    rows=(data??[]).map(s=><Card className="min-w-0" key={s.id}><CardHeader><CardTitle className="break-words">{s.material}</CardTitle><p className="text-sm text-muted-foreground">{names.get(s.student_id)??"Murid"} · <DateText value={s.session_date} tz={tz}/></p></CardHeader><CardContent className="space-y-3"><p className="text-sm font-medium">{s.sub_material}</p><p className="whitespace-pre-wrap text-sm">{s.learning_notes}</p><div className="flex flex-wrap gap-2"><ResourceEditor kind="material" label="Simpan ke Koleksi" initial={{title:s.material??"",content:[s.sub_material,s.learning_notes].filter(Boolean).join("\n\n"),source_session_id:s.id}}/><Button asChild variant="outline" size="sm"><Link href={`/sessions/${s.id}`}>Lihat Pertemuan</Link></Button></div></CardContent></Card>);
  } else if(kind==="material") {
    const {data,error,count}=await db.from("learning_materials").select("*",{count:"exact"}).eq("user_id",user.id).ilike("title",`%${q}%`).order("created_at",{ascending:false}).order("id").range(from,from+19);if(error)throw new Error("Materi belum dapat dimuat.");total=count??0;
    rows=(data??[]).map(m=><Card className="min-w-0" key={m.id}><CardHeader><CardTitle className="break-words">{m.title}</CardTitle></CardHeader><CardContent className="space-y-4"><p className="whitespace-pre-wrap break-words text-sm">{m.content}</p><FileLinks files={m.files as unknown as LearningFile[]} kind="material" id={m.id}/><div className="flex flex-wrap gap-2"><ResourceEditor kind="material" initial={{...m}}/><ResourceDelete kind="material" id={m.id} title={m.title}/></div></CardContent></Card>);
  } else {
    let request=db.from("homework_tasks").select("*",{count:"exact"}).eq("user_id",user.id).eq("status",tab==="completed"?"completed":"assigned").ilike("title",`%${q}%`);if(query.student)request=request.eq("student_id",query.student);
    const {data,error,count}=await request.order("due_date",{nullsFirst:false}).order("created_at",{ascending:false}).order("id").range(from,from+19);if(error)throw new Error("Tugas belum dapat dimuat.");total=count??0;const today=formatInTimeZone(new Date(),tz,"yyyy-MM-dd");
    rows=(data??[]).map(t=><Card className="min-w-0" key={t.id}><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle className="break-words">{t.title}</CardTitle>{t.status==="assigned"&&t.due_date&&t.due_date<today&&<Badge variant="destructive">Lewat Tenggat</Badge>}</div><p className="text-sm text-muted-foreground">{names.get(t.student_id)??"Murid"}{t.due_date&&<> · Tenggat: <DateText value={t.due_date} tz={tz}/></>}</p></CardHeader><CardContent className="space-y-4"><p className="whitespace-pre-wrap break-words text-sm">{t.description}</p><FileLinks files={t.files as unknown as LearningFile[]} kind="homework" id={t.id}/><div className="flex flex-wrap gap-2"><HomeworkStatusButton id={t.id} status={t.status}/><ResourceEditor kind="homework" students={students??[]} initial={{...t}}/><ResourceDelete kind="homework" id={t.id} title={t.title}/></div></CardContent></Card>);
  }
  const href=(p:number)=>`${path}?${new URLSearchParams({tab,q,page:String(p),...(query.student?{student:query.student}:{})})}`;
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-bold">{kind==="material"?"Materi":"Tugas/PR"}</h1><ResourceEditor kind={kind} students={students??[]}/></div><nav aria-label="Bagian" className="flex flex-wrap gap-2">{tabs.map(([value,label])=><Button key={value} asChild variant={tab===value?"default":"outline"}><Link href={`${path}?tab=${value}`}>{label}</Link></Button>)}</nav><form className="flex flex-wrap gap-2"><input type="hidden" name="tab" value={tab}/><Input name="q" aria-label="Cari judul" placeholder="Cari judul…" defaultValue={q} className="w-full sm:w-72"/>{kind==="homework"&&<select name="student" aria-label="Filter murid" defaultValue={query.student??""} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">Semua murid</option>{students?.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select>}<Button variant="outline">Cari</Button></form><div className="grid gap-4 lg:grid-cols-2">{rows}</div>{!rows.length&&<div className="rounded-xl border bg-card p-10 text-center text-sm text-muted-foreground">{kind==="material"?"Belum ada materi.":"Belum ada tugas di bagian ini."}</div>}<div className="flex items-center justify-between gap-3 text-sm text-muted-foreground"><span>{total} data</span><div className="flex gap-2">{page>1&&<Button asChild variant="outline"><Link href={href(page-1)}>Sebelumnya</Link></Button>}{page*20<total&&<Button asChild variant="outline"><Link href={href(page+1)}>Berikutnya</Link></Button>}</div></div></div>;
}
export function FileLinks({files,kind,id,portal=false}:{files:LearningFile[];kind:"material"|"homework";id:string;portal?:boolean}) {return <div className="flex flex-wrap gap-2">{files.map((f,index)=><Button key={f.path} asChild size="sm" variant="outline" className="h-auto max-w-full py-2"><a href={`${portal?"/portal/files":"/learning-files"}/${id}/${index}?kind=${kind}`} target="_blank" rel="noopener noreferrer" className="break-all whitespace-normal">{f.name}</a></Button>)}</div>;}
