import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { getSiteConfig } from "@/lib/admin";
import { TicketForm } from "@/components/support/ticket-form";
import { Card,CardHeader,CardTitle,CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { DateText } from "@/components/shared/date-text";
import type { SupportTicket } from "@/types/admin.types";
export default async function SupportPage({searchParams}:{searchParams:Promise<{tab?:string}>}){
 const {tab}=await searchParams;const active=tab==="announcements"?"announcements":"tickets";const db=await createClient();const {data,error}=await db.rpc("teacher_support",{p_action:active});if(error)throw new Error("Dukungan belum dapat dimuat.");const config=await getSiteConfig();
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-bold">Dukungan</h1>{config.support_email&&<Button variant="outline" asChild><a href={`mailto:${config.support_email}`}>Hubungi Dukungan</a></Button>}</div><div className="flex gap-2"><Button variant={active==="tickets"?"default":"outline"} asChild><Link href="/support">Tiket Saya</Link></Button><Button variant={active==="announcements"?"default":"outline"} asChild><Link href="/support?tab=announcements">Pengumuman</Link></Button></div>{active==="tickets"?<><Card><CardHeader><CardTitle>Buat Tiket</CardTitle></CardHeader><CardContent><TicketForm/></CardContent></Card>{(data as unknown as SupportTicket[]).map(t=><Card key={t.id}><CardHeader><CardTitle>{t.subject}</CardTitle><p className="text-sm text-muted-foreground">{{open:"Terbuka",in_progress:"Ditangani",resolved:"Selesai"}[t.status]??t.status} · <DateText value={t.created_at} tz="Asia/Jakarta"/></p></CardHeader><CardContent className="space-y-4"><p className="whitespace-pre-wrap break-words text-sm">{t.message}</p>{t.reply&&<div className="rounded-xl bg-muted p-4"><p className="mb-2 text-sm font-semibold">Balasan Dukungan</p><p className="whitespace-pre-wrap break-words text-sm">{t.reply}</p></div>}</CardContent></Card>)}</>:<>{(data as unknown as {id:string;title:string;body:string;publish_at:string}[]).map(a=><Card key={a.id}><CardHeader><CardTitle>{a.title}</CardTitle><DateText value={a.publish_at} tz="Asia/Jakarta" className="text-xs text-muted-foreground"/></CardHeader><CardContent><p className="whitespace-pre-wrap break-words text-sm">{a.body}</p></CardContent></Card>)}{Array.isArray(data)&&!data.length&&<p className="rounded-xl border p-8 text-center text-sm text-muted-foreground">Belum ada pengumuman.</p>}</>}</div>;
}
