import Link from "next/link";
import { formatInTimeZone } from "date-fns-tz";
import { Activity, HeartHandshake, Star, Users } from "lucide-react";
import { AdminForm, AdminMutationButton, type AdminField } from "@/components/admin/admin-form";
import { StatCard } from "@/components/shared/stat-card";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { formatRupiah as formatIDR } from "@/lib/utils/currency";
import type { AdminDataMap, AdminRole, AdminSection } from "@/types/admin.types";

const date=(v:string|null)=>v?formatInTimeZone(v,"Asia/Jakarta","dd MMM yyyy HH:mm"):"Belum tersedia";
const local=(v:string|null)=>v?formatInTimeZone(v,"Asia/Jakarta","yyyy-MM-dd'T'HH:mm"):"";
const statusLabels:Record<string,string>={active:"Aktif",suspended:"Ditangguhkan",new:"Baru",read:"Dibaca",resolved:"Selesai",open:"Terbuka",in_progress:"Ditangani",draft:"Draf",scheduled:"Terjadwal",published:"Diterbitkan",cancelled:"Dibatalkan",ok:"Berhasil",error:"Gagal"};
const field=(name:string,label:string,type:AdminField["type"]="text"):AdminField=>({name,label,type});
const select=(name:string,label:string,values:string[]):AdminField=>({name,label,options:values.map(v=>[v,statusLabels[v]??v])});
export const ADMIN_TITLES:Record<AdminSection,string>={dashboard:"Dashboard Admin",accounts:"Akun Guru",reviews:"Review Website",tickets:"Dukungan Pengguna",services:"Pemantauan Layanan",announcements:"Pengumuman",reports:"Laporan Website",expenses:"Keuangan Website",settings:"Pengaturan Website",audit:"Catatan Akses Admin"};
function Panel({title,children}:{title:string;children:React.ReactNode}) {return <Card><CardHeader><CardTitle className="text-lg">{title}</CardTitle></CardHeader><CardContent className="space-y-4">{children}</CardContent></Card>;}
function Copy({children}:{children:React.ReactNode}) {return <p className="whitespace-pre-wrap break-words text-sm leading-relaxed">{children}</p>;}
function Filters({section,q,status,options}:{section:string;q:string;status:string;options:string[]}) {return <form action={`/admin/${section}`} className="flex flex-wrap gap-2"><Input name="q" aria-label="Cari" placeholder="Cari…" defaultValue={q} className="w-full sm:w-72"/><select name="status" aria-label="Status" defaultValue={status} className="rounded-md border bg-background px-3 text-sm"><option value="all">Semua status</option>{options.map(s=><option key={s} value={s}>{statusLabels[s]??s}</option>)}</select><Button variant="outline">Terapkan</Button></form>;}
function Pagination({section,page,total,q,status}:{section:string;page:number;total:number;q:string;status:string}) {const href=(p:number)=>`/admin/${section}?${new URLSearchParams({q,status,page:String(p)})}`;return <div className="flex flex-wrap items-center justify-between gap-3 text-sm text-muted-foreground"><span>{total} data · Halaman {page}</span><div className="flex gap-2">{page>1&&<Button asChild variant="outline" size="sm"><Link href={href(page-1)}>Sebelumnya</Link></Button>}{page*20<total&&<Button asChild variant="outline" size="sm"><Link href={href(page+1)}>Berikutnya</Link></Button>}</div></div>;}
export function AdminPageContent({section,data,role,userId,q,status}:{section:AdminSection;data:AdminDataMap[AdminSection];role:AdminRole;userId:string;q:string;status:string}) {
  let content:React.ReactNode;
  switch(section) {
    case "dashboard": {const d=data as AdminDataMap["dashboard"];const maximum=Math.max(1,...d.growth.map(g=>g.accounts));content=<><div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><StatCard icon={Users} label="Akun Terdaftar" value={d.teachers}/><StatCard icon={Activity} label="Aktif 30 Hari" value={d.active_accounts} tone="sky"/><StatCard icon={Star} label="Rating Website" value={`${d.review_average}/5`} tone="peach"/><StatCard icon={HeartHandshake} label="Tiket Terbuka" value={d.ticket_open} tone="lilac"/></div><div className="grid gap-4 lg:grid-cols-2"><Panel title="Pertumbuhan Akun · 30 Hari"><div className="flex h-36 items-end gap-1">{d.growth.map(g=><div key={g.day} className="flex-1 rounded-t bg-primary/70" style={{height:`${Math.max(2,g.accounts/maximum*100)}%`}} title={`${g.day}: ${g.accounts} akun`} aria-label={`${g.day}: ${g.accounts} akun`}/>)}</div><p className="text-sm">{d.new_accounts} akun baru · {d.suspended} ditangguhkan · {d.review_new} review baru</p></Panel><Panel title="Layanan Terakhir">{["send-push","announcements"].map(service=>{const run=d.service_last.find(r=>r.service===service);return <div key={service} className="rounded-lg border p-3"><p className="font-medium">{service==="send-push"?"Notifikasi pengingat":"Pengumuman"}</p><p className="text-sm text-muted-foreground">{run?`${statusLabels[run.outcome]} · ${date(run.created_at)} · ${run.failed} gagal`:"Belum ada hasil pemantauan"}</p></div>;})}<Button asChild variant="outline"><Link href="/admin/services">Lihat Layanan</Link></Button></Panel></div></>;break;}
    case "accounts": {const d=data as AdminDataMap["accounts"];content=<><Filters section={section} q={q} status={status} options={["active","suspended"]}/>{d.items.map(a=><Panel key={`${a.id}-${a.status}`} title={a.full_name||a.email}><div className="grid gap-2 text-sm sm:grid-cols-2"><p>{a.email}</p><p>{statusLabels[a.status]} · {a.email_verified?"Email terverifikasi":"Email belum terverifikasi"}</p><p>{a.student_count} murid · {a.session_count} pertemuan</p><p>Aktif terakhir: {date(a.last_seen_at)}</p><p>Bergabung: {date(a.created_at)}</p><p>{a.business_name??""}</p></div>{role==="owner"&&a.id!==userId&&!a.admin_active&&<AdminForm action="account" initial={{id:a.id,status:a.status,reason:a.reason}} fields={[select("status","Status akun",["active","suspended"]),field("reason","Alasan penangguhan","textarea")]} label="Ubah Status Akun" confirmation={`Perubahan berlaku pada akses ${a.email}, termasuk sesi yang sedang aktif.`}/>}</Panel>)}</>;break;}
    case "reviews": {const d=data as AdminDataMap["reviews"];content=<><Filters section={section} q={q} status={status} options={["new","read","resolved"]}/>{d.items.map(r=><Panel key={`${r.id}-${r.status}`} title={`${r.full_name} · ${r.rating}/5`}><Copy>{r.comment||"Tanpa komentar"}</Copy><p className="text-xs text-muted-foreground">{date(r.updated_at)}</p><AdminForm action="review" initial={{id:r.id,status:r.status,note:r.note}} fields={[select("status","Status",["new","read","resolved"]),field("note","Catatan internal","textarea")]}/></Panel>)}</>;break;}
    case "tickets": {const d=data as AdminDataMap["tickets"];content=<><Filters section={section} q={q} status={status} options={["open","in_progress","resolved"]}/>{d.items.map(t=><Panel key={`${t.id}-${t.updated_at}`} title={t.subject}><p className="text-sm text-muted-foreground">{t.full_name} · {date(t.created_at)}</p><Copy>{t.message}</Copy><AdminForm action="ticket" initial={{id:t.id,status:t.status,priority:t.priority,reply:t.reply,internal_note:t.internal_note}} fields={[select("status","Status",["open","in_progress","resolved"]),{name:"priority",label:"Prioritas",options:[["low","Rendah"],["normal","Normal"],["high","Tinggi"]]},field("reply","Balasan untuk guru","textarea"),field("internal_note","Catatan internal","textarea")]}/></Panel>)}</>;break;}
    case "services": {const d=data as AdminDataMap["services"];content=<><Filters section={section} q={q} status={status} options={["ok","error"]}/><Panel title="Hasil Pemantauan"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Waktu","Layanan","Hasil","Diproses","Terkirim","Gagal","Durasi"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{d.items.map(r=><tr key={r.id} className="border-t"><td className="whitespace-nowrap p-3">{date(r.created_at)}</td><td className="p-3">{r.service}</td><td className="p-3">{statusLabels[r.outcome]}{r.message&&<p className="text-xs text-muted-foreground">{r.message}</p>}</td><td className="p-3">{r.processed}</td><td className="p-3">{r.sent}</td><td className="p-3">{r.failed}</td><td className="p-3">{r.duration_ms} ms</td></tr>)}</tbody></table></div>{!d.items.length&&<p className="text-sm text-muted-foreground">Belum ada hasil pemantauan.</p>}</Panel></>;break;}
    case "announcements": {const d=data as AdminDataMap["announcements"];const fields:AdminField[]=[field("title","Judul"),field("body","Isi pengumuman","textarea"),{name:"audience",label:"Penerima",options:[["all","Semua akun"],["selected","Akun tertentu"]]},field("emails","Email penerima (pisahkan dengan koma)"),field("publish_at","Waktu terbit (WIB)","datetime-local"),field("expires_at","Berakhir (WIB)","datetime-local")];content=<>{role==="owner"&&<Panel title="Pengumuman Baru"><AdminForm action="announcement_save" fields={fields} initial={{audience:"all",publish_at:"",expires_at:""}} label="Simpan Draf"/></Panel>}<Filters section={section} q={q} status={status} options={["draft","scheduled","published","cancelled"]}/>{d.items.map(a=><Panel key={`${a.id}-${a.status}`} title={a.title}><Copy>{a.body}</Copy><p className="text-sm text-muted-foreground">{statusLabels[a.status]} · {a.target_users?`${a.target_users.length} akun`:"Semua akun"} · {date(a.publish_at)}</p>{role==="owner"&&a.status==="draft"&&<><details><summary className="cursor-pointer text-sm font-medium">Edit Draf</summary><div className="pt-4"><AdminForm action="announcement_save" fields={fields} initial={{...a,audience:a.target_users?"selected":"all",emails:(a.target_emails??[]).join(", "),publish_at:local(a.publish_at),expires_at:local(a.expires_at)}} label="Simpan Draf"/></div></details><AdminMutationButton action="announcement_publish" id={a.id} label="Terbitkan" description={`Terbitkan “${a.title}” untuk ${a.target_users?`${a.target_users.length} akun`:"semua akun"} pada ${date(a.publish_at)}? Pengumuman akan muncul di notifikasi penerima.`}/></>}{role==="owner"&&a.status!=="cancelled"&&<AdminMutationButton action="announcement_cancel" id={a.id} label="Batalkan" description={`Batalkan pengumuman “${a.title}”?`}/>}</Panel>)}</>;break;}
    case "reports": {const d=data as AdminDataMap["reports"];content=<Panel title="Laporan 12 Bulan"><Button asChild variant="outline"><Link href="/admin/export">Unduh CSV</Link></Button><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Bulan","Akun Baru","Review","Rating","Tiket",...(role==="owner"?["Biaya Website"]:[])].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{d.months.map(r=><tr key={r.month} className="border-t"><td className="p-3 whitespace-nowrap">{r.month}</td><td className="p-3">{r.accounts}</td><td className="p-3">{r.reviews}</td><td className="p-3">{r.rating}</td><td className="p-3">{r.tickets}</td>{role==="owner"&&<td className="p-3 whitespace-nowrap">{formatIDR(r.expense)}</td>}</tr>)}</tbody></table></div></Panel>;break;}
    case "expenses": {const d=data as AdminDataMap["expenses"];content=<><div className="grid gap-4 sm:grid-cols-2"><StatCard icon={Activity} label="Biaya Bulan Ini" value={formatIDR(d.month_total)}/><StatCard icon={Activity} label="Biaya Tahun Ini" value={formatIDR(d.year_total)} tone="peach"/></div><Panel title="Catat Biaya Website"><AdminForm action="expense" initial={{expense_date:formatInTimeZone(new Date(),"Asia/Jakarta","yyyy-MM-dd"),category:"hosting",description:"",amount:""}} fields={[field("expense_date","Tanggal","date"),{name:"category",label:"Kategori",options:[["hosting","Hosting"],["domain","Domain"],["tools","Perangkat kerja"],["other","Lainnya"]]},field("description","Keterangan"),field("amount","Nominal (Rp)","number")]} label="Simpan Biaya"/></Panel>{d.items.map(e=><Panel key={e.id} title={e.description}><p>{e.expense_date} · {e.category} · {formatIDR(e.amount)}</p><AdminMutationButton action="expense_archive" id={e.id} label="Arsipkan" description={`Arsipkan biaya “${e.description}”? Nominal akan dikeluarkan dari total biaya aktif.`}/></Panel>)}</>;break;}
    case "settings": {const d=data as AdminDataMap["settings"];content=<><Panel title="Identitas dan Layanan"><AdminForm action="settings" initial={{...d.config}} fields={[field("site_name","Nama website"),field("support_email","Email dukungan","email"),field("maintenance_mode","Mode pemeliharaan","checkbox")]} confirmation="Simpan pengaturan website? Mode pemeliharaan membatasi akses guru dan portal orang tua, sementara admin tetap dapat masuk."/></Panel><Panel title="Tambah Akses Admin"><AdminForm action="member" initial={{email:"",role:"support",active:true}} fields={[field("email","Email akun","email"),{name:"role",label:"Peran",options:[["support","Dukungan"],["owner","Pemilik website"]]},field("active","Akses aktif","checkbox")]} label="Simpan Akses" confirmation="Akun tujuan akan memperoleh akses admin sesuai peran yang dipilih dan wajib memakai verifikasi dua langkah."/></Panel><Panel title="Pengelola Website">{d.members.map(m=><div key={`${m.user_id}-${m.role}-${m.active}`} className="rounded-xl border p-4"><p className="font-medium">{m.full_name}</p><p className="mb-3 text-sm text-muted-foreground">{m.email} · {m.role==="owner"?"Pemilik":"Dukungan"} · {m.active?"Aktif":"Nonaktif"}</p>{m.user_id!==userId&&<AdminForm action="member" initial={{email:m.email,role:m.role,active:m.active}} fields={[{name:"role",label:"Peran",options:[["support","Dukungan"],["owner","Pemilik website"]]},field("active","Akses aktif","checkbox")]} confirmation={`Perbarui akses admin ${m.email}? Perubahan berlaku pada sesi yang sedang aktif.`}/>}</div>)}<Button asChild variant="outline"><Link href="/admin/audit">Catatan Akses Admin</Link></Button></Panel></>;break;}
    case "audit": {const d=data as AdminDataMap["audit"];content=<Panel title="Perubahan oleh Admin">{d.items.map(a=><div key={a.id} className="border-b pb-3"><p className="text-sm font-medium">{a.action} · {a.full_name??"Sistem"}</p><p className="break-all text-xs text-muted-foreground">{date(a.created_at)} · {a.target_id??"Website"}</p></div>)}</Panel>;break;}
  }
  const paged="items" in data?data:null;
  return <div className="space-y-5"><h1 className="text-2xl font-bold tracking-tight">{ADMIN_TITLES[section]}</h1>{content}{paged&&<>{!paged.items.length&&section!=="services"&&<p className="rounded-xl border p-6 text-center text-sm text-muted-foreground">Belum ada data.</p>}<Pagination section={section} page={paged.page} total={paged.total} q={q} status={status}/></>}</div>;
}
